### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by pietrodn** [middleware2016/hadoop-accidents#3]
The Hadoop tasks should run as fast as possible.
Move outside of the map() method all the things that can be precomputed (e.g. the formatters).

**Comment by carduz** [comment]
What do you mean with "formatters"? if this means format every record I think it should be put in the mapper since it is computed in a distributed way

**Comment by pietrodn** [comment]
I mean that objects like the date formatter can be initialized statically in the class and then applied to every record in the method. If we initialize them in map() we lose time.

**Comment by giuanbalina** [comment]
The formatter is not thread-safe so a static initialisation can not be a good idea. I searched around and seems that It is expensive to initialise a SimpleDateFromat. They proposed also a static initialisation with a locking system, but for us I think it is not a good idea. Otherwise they propose a solution using a new date formatter, but requires Java8. It is immutable. It is the class DateTimeFormatter, but does not return a Date, so some manipulation is required.

http://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

http://stackoverflow.com/questions/4107839/synchronizing-access-to-simpledateformat

**Comment by pietrodn** [comment]
Another idea: add combiners where not present.

**Comment by giuanbalina** [comment]
Done
